extends Node

# What a stock SceneMultiplayer puts on the wire for an RPC with arguments.
#
#   godot --headless --path oracle res://rpc_oracle.tscn
#
# ## Why a fake peer rather than a capture
#
# The rest of this crate was measured from two peers playing a real game, and
# that corpus has no RPC with arguments in it -- the demo it came from never
# calls one. Rather than guess the layout, this asks the engine directly: a
# `MultiplayerPeerExtension` is a peer as far as `SceneMultiplayer` is
# concerned, so the stock API encodes the call exactly as it would for a
# socket and hands the bytes here instead of sending them.
#
# One process, no network, no packet capture and no root. The bytes are the
# engine's own; only their destination changed.
#
# ## The argument set is chosen to break a careless decoder
#
# Not one of each type -- the Variant codec is already tested against every
# type by `variant_oracle.gd`. What matters here is the *framing* around them:
# zero arguments against one, one against many, a type whose length is fixed
# against one that carries its own, and an argument big enough that the
# offset field cannot be a byte.

class RecordingPeer extends MultiplayerPeerExtension:
	# Every packet the API tried to send, in order.
	var sent: Array[PackedByteArray] = []
	# What the API is told to read. Left empty: nothing here replies.
	var _incoming: Array[PackedByteArray] = []

	# Hands the API a packet as though it had arrived from peer 2.
	func deliver(packet: PackedByteArray) -> void:
		_incoming.append(packet)

	func _get_unique_id() -> int:
		return 1  # the server, so calls route outward rather than to a host

	func _get_connection_status() -> int:
		return MultiplayerPeer.CONNECTION_CONNECTED

	func _is_server() -> bool:
		return true

	func _is_server_relay_supported() -> bool:
		return false

	func _put_packet_script(buffer: PackedByteArray) -> int:
		sent.append(buffer.duplicate())
		return OK

	func _get_packet_script() -> PackedByteArray:
		return _incoming.pop_front() if not _incoming.is_empty() else PackedByteArray()

	func _get_available_packet_count() -> int:
		return _incoming.size()

	func _get_max_packet_size() -> int:
		return 1 << 24

	func _poll() -> void:
		pass

	func _close() -> void:
		pass

	func _disconnect_peer(_peer: int, _force: bool) -> void:
		pass

	func _set_target_peer(_peer: int) -> void:
		pass

	func _get_packet_peer() -> int:
		return 2

	func _get_packet_channel() -> int:
		return 0

	func _get_packet_mode() -> int:
		return MultiplayerPeer.TRANSFER_MODE_RELIABLE

	func _set_transfer_channel(_channel: int) -> void:
		pass

	func _get_transfer_channel() -> int:
		return 0

	func _set_transfer_mode(_mode: int) -> void:
		pass

	func _get_transfer_mode() -> int:
		return MultiplayerPeer.TRANSFER_MODE_RELIABLE

	func _set_refuse_new_connections(_enable: bool) -> void:
		pass

	func _is_refusing_new_connections() -> bool:
		return false


# The methods whose calls are dumped. Sorted by name, the ids are:
#   0 no_args, 1 one_int, 2 one_string, 3 three_mixed, 4 two_vectors
# which is the same numbering `rpc.rs` derives, and worth stating because the
# id in the packet is an index into that sorted list rather than a hash.
@rpc("any_peer", "call_remote", "reliable")
func no_args() -> void:
	pass


@rpc("any_peer", "call_remote", "reliable")
func one_int(_a: int) -> void:
	pass


@rpc("any_peer", "call_remote", "reliable")
func one_string(_a: String) -> void:
	pass


@rpc("any_peer", "call_remote", "reliable")
func two_vectors(_a: Vector3, _b: Vector3) -> void:
	pass


@rpc("any_peer", "call_remote", "reliable")
func three_mixed(_a: int, _b: String, _c: bool) -> void:
	pass


var _peer := RecordingPeer.new()


func _ready() -> void:
	print("# RPC call framing, godot %s" % Engine.get_version_info()["string"])
	print("# Encoded by a stock SceneMultiplayer into a recording peer.")
	print("# Generated by oracle/rpc_oracle.gd -- regenerate, do not edit.")
	print("#")
	print("# <label>\t<hex>")

	multiplayer.multiplayer_peer = _peer
	# The API keeps its own peer list and will not address a call to a peer it
	# has not been told about. This is the signal a real peer emits when a
	# socket connects.
	_peer.peer_connected.emit(2)
	await get_tree().process_frame

	await _call_and_dump("no_args", [])
	await _call_and_dump("one_int 0", [0])
	await _call_and_dump("one_int 1", [1])
	await _call_and_dump("one_int -1", [-1])
	await _call_and_dump("one_int 2^33", [8589934592])
	await _call_and_dump("one_string empty", [""])
	await _call_and_dump("one_string ascii", ["shoot"])
	# Long enough that a one-byte length or offset cannot hold it.
	await _call_and_dump("one_string 300 bytes", ["x".repeat(300)])
	await _call_and_dump("two_vectors", [Vector3(1.0, -2.0, 3.0), Vector3(-4.0, 5.0, -6.0)])
	await _call_and_dump("three_mixed", [5, "hit", true])

	# Everything above addresses the node by path, because the receiver has
	# not confirmed the cache id the first SIMPLIFY_PATH offered. Confirming
	# it is a six-byte packet, and after it the same calls take the short
	# form -- which is the pair the crate has to tell apart.
	#
	# CONFIRM_PATH is [0x02][valid][u32 id], and the id is the one the
	# SIMPLIFY_PATH above carried.
	var confirm := PackedByteArray([0x02, 0x01, 0x01, 0x00, 0x00, 0x00])
	_peer.deliver(confirm)
	await get_tree().process_frame
	await get_tree().process_frame

	await _call_and_dump("cached no_args", [], "no_args")
	await _call_and_dump("cached one_int 7", [7], "one_int")
	await _call_and_dump("cached three_mixed", [5, "hit", true], "three_mixed")

	get_tree().quit()


func _call_and_dump(label: String, args: Array, method: String = "") -> void:
	if method.is_empty():
		method = label.split(" ")[0]
	_peer.sent.clear()
	# rpc_id(2, ...) so the call is addressed to the peer above rather than
	# broadcast; a broadcast would encode the same body with a different target
	# and this is the one that matches a capture.
	callv("rpc_id", [2, method] + args)
	await get_tree().process_frame
	if _peer.sent.is_empty():
		print("%s\tNOTHING SENT" % label)
		return
	for packet in _peer.sent:
		print("%s\t%s" % [label, packet.hex_encode()])
