extends Node

# Ground truth for every Variant type this crate can carry.
#
#   godot --headless --path oracle res://variant_oracle.tscn
#
# ## Why the engine is asked rather than the documentation
#
# This crate has to encode and decode exactly what Godot does, and "exactly" is
# the word that carries the weight: a field whose float is one byte out of
# place decodes to a plausible number, not to an error, and a plausible number
# is a bug that never announces itself. `var_to_bytes()` is the script-visible
# side of the same `encode_variant` the replication protocol uses, so what it
# prints is ground truth rather than a reading of the format.
#
# ## Two values per type, and neither of them zero-shaped
#
# Each type is dumped twice: once at its zero or default, and once at a value
# whose bytes are distinctive in every field. A decoder written against a
# single zeroed sample passes by returning zeroes, and a decoder written
# against symmetric values passes with its axes swapped. Both have happened in
# this protocol.
#
# ## What is deliberately absent
#
# Object, Callable, Signal and RID encode a pointer or an instance id that
# means nothing at the far end. `var_to_bytes` will write them only with
# `full_objects` set, and a replication protocol that accepted them would be
# handing a remote peer a deserialization primitive. They are refused by the
# crate rather than implemented, and they are not dumped here.

func _ready() -> void:
	print("# Variant ground truth, godot %s" % Engine.get_version_info()["string"])
	print("# var_to_bytes(), the script-visible encode_variant.")
	print("# Generated by oracle/variant_oracle.gd -- regenerate, do not edit.")
	print("#")
	print("# <label>\t<type id>\t<hex>")

	_dump("nil", null)

	_dump("bool false", false)
	_dump("bool true", true)

	_dump("int 0", 0)
	_dump("int 1", 1)
	_dump("int -1", -1)
	_dump("int 2^33", 8589934592)
	_dump("int min64", -9223372036854775808)

	_dump("float 0.0", 0.0)
	_dump("float -6.3808", -6.3808)
	_dump("float 1e300", 1e300)

	_dump("String empty", "")
	_dump("String ascii", "RedRobot")
	# Length is in bytes and padded to four; a decoder that counts characters
	# or forgets the padding survives ASCII and dies here.
	_dump("String utf8", "smörgås—あ")

	_dump("Vector2 zero", Vector2())
	_dump("Vector2 asym", Vector2(1.0, -2.0))
	_dump("Vector2i zero", Vector2i())
	_dump("Vector2i asym", Vector2i(1, -2))

	_dump("Rect2 zero", Rect2())
	_dump("Rect2 asym", Rect2(1.0, -2.0, 3.0, -4.0))
	_dump("Rect2i zero", Rect2i())
	_dump("Rect2i asym", Rect2i(1, -2, 3, -4))

	_dump("Vector3 zero", Vector3())
	_dump("Vector3 marker", Vector3(71.5907, -6.3808, 46.2736))
	_dump("Vector3i zero", Vector3i())
	_dump("Vector3i asym", Vector3i(1, -2, 3))

	_dump("Vector4 zero", Vector4())
	_dump("Vector4 asym", Vector4(1.0, -2.0, 3.0, -4.0))
	_dump("Vector4i zero", Vector4i())
	_dump("Vector4i asym", Vector4i(1, -2, 3, -4))

	_dump("Transform2D identity", Transform2D())
	_dump("Transform2D asym", Transform2D(
			Vector2(1.0, -2.0), Vector2(3.0, -4.0), Vector2(5.0, -6.0)))

	_dump("Plane zero", Plane())
	_dump("Plane asym", Plane(Vector3(0.0, 1.0, 0.0), -3.5))

	_dump("Quaternion identity", Quaternion())
	_dump("Quaternion asym", Quaternion(0.1, -0.2, 0.3, 0.9273618))

	_dump("AABB zero", AABB())
	_dump("AABB asym", AABB(Vector3(1.0, -2.0, 3.0), Vector3(-4.0, 5.0, -6.0)))

	_dump("Basis identity", Basis())
	# Marker3D1's own basis: a yaw of -0.5663 rad, so no two rows agree.
	var turned_basis := Basis(
			Vector3(0.843905, 0.0, -0.536493),
			Vector3(0.0, 1.0, 0.0),
			Vector3(0.536493, 0.0, 0.843905))
	_dump("Basis yawed", turned_basis)

	_dump("Transform3D identity", Transform3D())
	_dump("Transform3D marker", Transform3D(
			turned_basis, Vector3(71.5907, -6.3808, 46.2736)))

	_dump("Projection identity", Projection())
	_dump("Projection asym", Projection(
			Vector4(1.0, -2.0, 3.0, -4.0),
			Vector4(5.0, -6.0, 7.0, -8.0),
			Vector4(9.0, -10.0, 11.0, -12.0),
			Vector4(13.0, -14.0, 15.0, -16.0)))

	_dump("Color zero", Color(0.0, 0.0, 0.0, 0.0))
	_dump("Color asym", Color(0.25, 0.5, 0.75, 1.0))

	_dump("StringName empty", StringName(""))
	_dump("StringName shoot", StringName("shoot"))

	_dump("NodePath empty", NodePath(""))
	_dump("NodePath absolute", NodePath("/root/Level/SpawnedNodes/RedRobot"))
	_dump("NodePath subname", NodePath("Player:position:x"))

	# A dictionary and an array carry their elements as nested Variants, so
	# these exercise the recursion rather than a new leaf format.
	_dump("Dictionary empty", {})
	_dump("Dictionary mixed", {"health": 5, "dead": false, "at": Vector3(1.0, -2.0, 3.0)})

	_dump("Array empty", [])
	_dump("Array mixed", [1, "two", 3.0, false, Vector2(5.0, -6.0)])
	_dump("Array nested", [[1, 2], {"k": "v"}])

	_dump("PackedByteArray empty", PackedByteArray())
	_dump("PackedByteArray bytes", PackedByteArray([0, 1, 127, 128, 255]))

	_dump("PackedInt32Array empty", PackedInt32Array())
	_dump("PackedInt32Array asym", PackedInt32Array([0, 1, -2, 2147483647]))

	_dump("PackedInt64Array empty", PackedInt64Array())
	_dump("PackedInt64Array asym", PackedInt64Array([0, -1, 8589934592]))

	_dump("PackedFloat32Array empty", PackedFloat32Array())
	_dump("PackedFloat32Array asym", PackedFloat32Array([0.0, -1.5, 3.25]))

	_dump("PackedFloat64Array empty", PackedFloat64Array())
	_dump("PackedFloat64Array asym", PackedFloat64Array([0.0, -1.5, 1e300]))

	_dump("PackedStringArray empty", PackedStringArray())
	_dump("PackedStringArray asym", PackedStringArray(["", "a", "smörgås"]))

	_dump("PackedVector2Array empty", PackedVector2Array())
	_dump("PackedVector2Array asym", PackedVector2Array([
			Vector2(0.0, 0.0), Vector2(1.0, -2.0)]))

	_dump("PackedVector3Array empty", PackedVector3Array())
	_dump("PackedVector3Array asym", PackedVector3Array([
			Vector3(0.0, 0.0, 0.0), Vector3(1.0, -2.0, 3.0)]))

	_dump("PackedColorArray empty", PackedColorArray())
	_dump("PackedColorArray asym", PackedColorArray([
			Color(0.0, 0.0, 0.0, 0.0), Color(0.25, 0.5, 0.75, 1.0)]))

	_dump("PackedVector4Array empty", PackedVector4Array())
	_dump("PackedVector4Array asym", PackedVector4Array([
			Vector4(0.0, 0.0, 0.0, 0.0), Vector4(1.0, -2.0, 3.0, -4.0)]))

	_round_trip()
	get_tree().quit()


# Every value dumped above, put back through the engine. A dump of something
# the engine cannot itself read back is a dump of a bug, and it would be this
# crate that inherited it.
func _round_trip() -> void:
	var values: Array = [
		null, false, true, 0, -1, 8589934592, 0.0, -6.3808, "", "RedRobot",
		"smörgås—あ",
		Vector2(1.0, -2.0), Vector2i(1, -2), Rect2(1.0, -2.0, 3.0, -4.0),
		Rect2i(1, -2, 3, -4), Vector3(71.5907, -6.3808, 46.2736),
		Vector3i(1, -2, 3), Vector4(1.0, -2.0, 3.0, -4.0), Vector4i(1, -2, 3, -4),
		Transform2D(Vector2(1.0, -2.0), Vector2(3.0, -4.0), Vector2(5.0, -6.0)),
		Plane(Vector3(0.0, 1.0, 0.0), -3.5),
		Quaternion(0.1, -0.2, 0.3, 0.9273618),
		AABB(Vector3(1.0, -2.0, 3.0), Vector3(-4.0, 5.0, -6.0)),
		Basis(), Transform3D(), Projection(), Color(0.25, 0.5, 0.75, 1.0),
		StringName("shoot"), NodePath("Player:position:x"),
		{"health": 5}, [1, "two", 3.0],
		PackedByteArray([0, 255]), PackedInt32Array([-2, 2147483647]),
		PackedInt64Array([8589934592]), PackedFloat32Array([-1.5]),
		PackedFloat64Array([1e300]), PackedStringArray(["a"]),
		PackedVector2Array([Vector2(1.0, -2.0)]),
		PackedVector3Array([Vector3(1.0, -2.0, 3.0)]),
		PackedColorArray([Color(0.25, 0.5, 0.75, 1.0)]),
		PackedVector4Array([Vector4(1.0, -2.0, 3.0, -4.0)]),
	]
	var failures := 0
	for value in values:
		var back: Variant = bytes_to_var(var_to_bytes(value))
		if str(back) != str(value):
			push_error("round trip changed %s into %s" % [str(value), str(back)])
			failures += 1
	print("# round trip: %d values, %d failures" % [values.size(), failures])


func _dump(label: String, value: Variant) -> void:
	var bytes: PackedByteArray = var_to_bytes(value)
	# The type id the engine wrote, which is what the crate switches on. Taken
	# from the encoding rather than from typeof(), so that a disagreement
	# between the two shows up here rather than in a decoder.
	var type_id := bytes.decode_u16(0) if bytes.size() >= 2 else -1
	print("%s\t%d\t%s" % [label, type_id, bytes.hex_encode()])
